### PR TITLE
Clean up code styling; update Instructions, profile pic, vCard and Yellow Pages styling

### PR DESCRIPTION
**Pull request by skoolbus39**
- Update URL in Grunt to retrieve 4.1 Less mixins
- Remove unused inner-band-margin variable
- Update code style (fix indentation, alphabetize rules, reduce nesting of rules)
- Adjust Instructions (home) page card styling
- Add flex-shrink 0 to listing profile pics to prevent images from being squeezed horizontally by adjacent text
- Embolden ‘headlines’ that aren’t in heading tags
- Fix vCard tools calc() with escaped string for Less
- Replace Yellow Pages styles with utility classes

### CODE REVIEW

**Comment by ericras** [comment]
The embedded html/vcards need to be checked that they don't blow up aaron's sites

**Comment by skoolbus39** [comment]
@ericras Good call. I'll check them and report back.

**Comment by skoolbus39** [comment]
As far as I can tell, I see no issues removing the margin utilities from the vCards.

**Comment by ericras** [comment]
I have it deployed to directory-test - we should go through it together to make sure we're on the same page

**Comment by jsturek** [comment]
These changes look good to me. Reviewed on directory-test.

**Comment by ericras** [comment]
building images overflow the container

screen shot 2019-02-05 at 10 54 35 am

**Comment by skoolbus39** [comment]
I think my latest commits should fix the building image overflows.

**Pull request merged**
